#include "ei1333/template/template.cpp"

// add your library with double quotation #include"" here.
#include "atcoder/all"
using namespace atcoder;

// define your macros here.
#define REP(a,b) for(int a = 0;a < b;++a)
#define ALL(a) (a).begin(),(a).end()
#define END(a) { cout << (a) << '\n'; return; }
using ll = long long;
using P = pair<int, int>;
using VI = vector<int>;
using VVI = vector<VI>;
using VVVI = vector<VVI>;
using VL = vector<ll>;
using VVL = vector<VL>;
using VVVL = vector<VVL>;
using VP = vector<P>;
using VVP = vector<VP>;
using VVVP = vector<VVP>;
using VD = vector<double>;
using VVD = vector<VD>;
using VVVD = vector<VVD>;
using MI7 = modint1000000007;
using MI3 = modint998244353;
constexpr int INF = 1001001001;
constexpr ll LINF = 1001001001001001001ll;

void solve(){
    // write your solution here.
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main() {
    // Fasterize input/output script
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    cout << fixed << setprecision(100);
    // scanf/printf user should delete this fasterize input/output script

    int t = 1;
    //cin >> t; // comment out if solving multi testcase
    for(int testCase = 1;testCase <= t;++testCase){
        solve();
    }
    return 0;
}